version: '3'
services:
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    networks:
      - overlay

  nodejs:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - overlay
    environment:
      - ENV=development
      - PORT=3000
      - HOST=localhost
      - MONGO_HOST=mongo:27017
    volumes:
      - .:/usr/src/app

networks:
  overlay: